import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Download, Search, Filter, Building, MapPin, Users, Target, Award } from "lucide-react";

const Dashboard = () => {
  return (
    <div className="min-h-screen bg-dashboard-gradient text-foreground">
      {/* Header */}
      <header className="border-b border-border/50 backdrop-blur-sm bg-background/5">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="animate-fade-in">
              <h1 className="text-2xl font-bold text-foreground">PE CFO Recruitment Dashboard</h1>
              <p className="text-muted-foreground">Finatal • AI-Powered CFO Search</p>
            </div>
            <div className="flex items-center gap-6">
              <div className="flex items-center gap-4 text-sm">
                <span className="text-muted-foreground">
                  <span className="text-2xl font-bold text-foreground">0</span> candidates
                </span>
                <span className="text-muted-foreground">•</span>
                <span className="text-muted-foreground">
                  <span className="text-accent font-semibold">3</span> active projects
                </span>
              </div>
              <Button variant="outline" size="sm" className="gap-2">
                <Download className="w-4 h-4" />
                Export
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Sidebar */}
          <div className="lg:col-span-1 space-y-6 animate-slide-in">
            {/* Current Project */}
            <Card className="bg-card-gradient border-border/50 backdrop-blur-sm">
              <div className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-semibold text-foreground">Current Project:</h3>
                  <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground">
                    <Filter className="w-4 h-4" />
                  </Button>
                </div>
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-secondary rounded-lg flex items-center justify-center">
                      <Building className="w-5 h-5 text-secondary-foreground" />
                    </div>
                    <div>
                      <h4 className="font-medium text-foreground">TechMed Healthcare</h4>
                      <p className="text-sm text-muted-foreground">Summit Capital</p>
                    </div>
                  </div>
                  
                  <div className="space-y-3 text-sm">
                    <div className="flex items-center gap-2">
                      <span className="text-muted-foreground">Industry:</span>
                      <span className="text-foreground">Healthcare Technology</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-muted-foreground">Locations:</span>
                      <span className="text-foreground">45+</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <MapPin className="w-3 h-3 text-muted-foreground" />
                      <span className="text-foreground">Atlanta, GA</span>
                    </div>
                  </div>

                  <div className="p-3 bg-secondary/50 rounded-lg border border-border/30">
                    <p className="text-sm text-muted-foreground mb-2">
                      Summit Capital owns 45-location healthcare system in Atlanta
                    </p>
                  </div>

                  <Badge className="bg-success/20 text-success border-success/30 hover:bg-success/30">
                    <Award className="w-3 h-3 mr-1" />
                    AI Template Active
                  </Badge>
                  <p className="text-xs text-muted-foreground">
                    Intelligent search parameters generated by GPT-4
                  </p>
                </div>

                <div className="space-y-3 mt-6">
                  <Button className="w-full bg-info hover:bg-info/90 text-white">
                    <Search className="w-4 h-4 mr-2" />
                    Search LinkedIn
                  </Button>
                  <Button variant="outline" className="w-full">
                    <Filter className="w-4 h-4 mr-2" />
                    Edit Project
                  </Button>
                </div>
              </div>
            </Card>

            {/* Smart Filters */}
            <Card className="bg-card-gradient border-border/50 backdrop-blur-sm">
              <div className="p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Filter className="w-4 h-4 text-accent" />
                  <h3 className="font-semibold text-foreground">Smart Filters</h3>
                </div>
                
                <div className="space-y-4">
                  <div>
                    <label className="text-sm font-medium text-foreground mb-2 block">
                      Min AI Score
                    </label>
                    <Slider
                      defaultValue={[0]}
                      max={100}
                      step={1}
                      className="w-full"
                    />
                    <div className="flex justify-between text-xs text-muted-foreground mt-1">
                      <span>0</span>
                      <span>100</span>
                    </div>
                  </div>

                  <div>
                    <label className="text-sm font-medium text-foreground mb-2 block">
                      Qualification Level
                    </label>
                    <Select defaultValue="all">
                      <SelectTrigger className="bg-secondary border-border">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Levels</SelectItem>
                        <SelectItem value="high">High</SelectItem>
                        <SelectItem value="medium">Medium</SelectItem>
                        <SelectItem value="low">Low</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <label className="text-sm font-medium text-foreground mb-2 block">
                      Recommendation
                    </label>
                    <Select defaultValue="all">
                      <SelectTrigger className="bg-secondary border-border">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Recommendations</SelectItem>
                        <SelectItem value="strong">Strong</SelectItem>
                        <SelectItem value="moderate">Moderate</SelectItem>
                        <SelectItem value="weak">Weak</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>
            </Card>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-3 space-y-6 animate-fade-in">
            {/* Project Header */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <span className="text-sm text-muted-foreground">45+ locations • Atlanta, GA</span>
                <Badge className="bg-success/20 text-success border-success/30">
                  <Award className="w-3 h-3 mr-1" />
                  AI Template Active
                </Badge>
              </div>
            </div>

            {/* Metrics Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: "Total", value: "0", color: "text-muted-foreground" },
                { label: "High Priority", value: "0", color: "text-warning" },
                { label: "Qualified", value: "0", color: "text-success" },
                { label: "PE Exp", value: "0", color: "text-accent" }
              ].map((metric, index) => (
                <Card key={metric.label} className="bg-card-gradient border-border/50 backdrop-blur-sm hover:border-primary/30 transition-all duration-300">
                  <div className="p-6 text-center">
                    <div className={`text-3xl font-bold mb-1 ${metric.color}`}>
                      {metric.value}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {metric.label}
                    </div>
                  </div>
                </Card>
              ))}
            </div>

            {/* Main Content Area */}
            <Card className="bg-card-gradient border-border/50 backdrop-blur-sm min-h-[400px]">
              <div className="p-8 flex flex-col items-center justify-center text-center">
                <div className="w-16 h-16 bg-secondary rounded-full flex items-center justify-center mb-6">
                  <Users className="w-8 h-8 text-secondary-foreground" />
                </div>
                <h3 className="text-xl font-semibold text-foreground mb-2">
                  No candidates yet
                </h3>
                <p className="text-muted-foreground mb-6 max-w-md">
                  Start a LinkedIn search to find CFO candidates for your TechMed Healthcare project
                </p>
                <Button size="lg" className="bg-primary hover:bg-primary/90 animate-glow">
                  <Search className="w-5 h-5 mr-2" />
                  Search LinkedIn Now
                </Button>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;