import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Download, Search, Filter, Building, MapPin, Users, Target, Award, TrendingUp, Globe, ChevronDown } from "lucide-react";

const Dashboard = () => {
  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(135deg, #1a0f2e 0%, #2d1b4e 50%, #1a0f2e 100%)' }}>
      {/* Header */}
      <header className="border-b border-white/10 backdrop-blur-xl bg-black/20 sticky top-0 z-50">
        <div className="container mx-auto px-8 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-white tracking-tight">PE CFO Recruitment Dashboard</h1>
              <p className="text-gray-400 text-sm mt-1">Finatal • AI-Powered CFO Search</p>
            </div>
            <div className="flex items-center gap-8">
              <div className="flex items-center gap-6 text-sm">
                <div className="text-center">
                  <div className="text-2xl font-bold text-white">0</div>
                  <div className="text-gray-400 text-xs uppercase tracking-wider">candidates</div>
                </div>
                <div className="w-px h-8 bg-white/20"></div>
                <div className="text-center">
                  <div className="text-xl font-semibold" style={{ color: 'hsl(271 81% 56%)' }}>3</div>
                  <div className="text-gray-400 text-xs uppercase tracking-wider">active projects</div>
                </div>
              </div>
              <Button variant="outline" size="default" className="gap-2 border-white/20 text-white hover:bg-white/10 transition-all duration-200">
                <Download className="w-4 h-4" />
                Export
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Sidebar */}
          <div className="lg:col-span-1 space-y-6">
            {/* Current Project */}
            <div className="bg-white/5 border border-white/10 rounded-xl backdrop-blur-sm">
              <div className="p-6">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-semibold text-white text-lg">Current Project</h3>
                  <ChevronDown className="w-4 h-4 text-gray-400" />
                </div>
                
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-white/10 rounded-lg flex items-center justify-center">
                      <Building className="w-5 h-5 text-white" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-white">TechMed Healthcare</h4>
                      <p className="text-sm text-gray-400">Summit Capital • Healthcare Technology</p>
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <div className="text-gray-400 text-xs uppercase tracking-wider mb-1">Industry</div>
                      <div className="text-white font-medium">Healthcare Technology</div>
                    </div>
                    <div>
                      <div className="text-gray-400 text-xs uppercase tracking-wider mb-1">Locations</div>
                      <div className="text-white font-medium">45+</div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-sm">
                    <MapPin className="w-4 h-4" style={{ color: 'hsl(271 81% 56%)' }} />
                    <span className="text-white font-medium">Atlanta, GA</span>
                    <span className="text-gray-400 ml-auto">45+ locations</span>
                  </div>

                  <div className="p-3 bg-white/5 rounded-lg border border-white/10">
                    <p className="text-sm text-gray-300">
                      Summit Capital owns 45-location healthcare system in Atlanta
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge className="bg-green-500/20 text-green-400 border-green-500/30 px-3 py-1">
                      AI Template Active
                    </Badge>
                  </div>
                  <p className="text-xs text-gray-400">
                    Intelligent search parameters generated by GPT-4
                  </p>
                </div>

                <div className="space-y-3 mt-6">
                  <Button className="w-full bg-cyan-500 hover:bg-cyan-600 text-white font-medium py-3">
                    <Search className="w-4 h-4 mr-2" />
                    Search LinkedIn
                  </Button>
                  <Button variant="outline" className="w-full py-3 border-white/20 text-white hover:bg-white/10">
                    <Filter className="w-4 h-4 mr-2" />
                    Edit Project
                  </Button>
                </div>
              </div>
            </div>

            {/* Smart Filters */}
            <div className="bg-white/5 border border-white/10 rounded-xl backdrop-blur-sm">
              <div className="p-6">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-8 h-8 bg-white/10 rounded-lg flex items-center justify-center">
                    <Filter className="w-4 h-4 text-white" />
                  </div>
                  <h3 className="font-semibold text-white">Smart Filters</h3>
                </div>
                
                <div className="space-y-4">
                  <div>
                    <label className="text-sm font-medium text-white mb-3 block">
                      Min AI Score
                    </label>
                    <Slider
                      defaultValue={[0]}
                      max={100}
                      step={1}
                      className="w-full"
                    />
                    <div className="flex justify-between text-xs text-gray-400 mt-2">
                      <span>0</span>
                      <span>100</span>
                    </div>
                  </div>

                  <div>
                    <label className="text-sm font-medium text-white mb-3 block">
                      Qualification Level
                    </label>
                    <Select defaultValue="all">
                      <SelectTrigger className="bg-white/10 border-white/20 text-white">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-gray-900 border-gray-700">
                        <SelectItem value="all">All Levels</SelectItem>
                        <SelectItem value="high">High</SelectItem>
                        <SelectItem value="medium">Medium</SelectItem>
                        <SelectItem value="low">Low</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <label className="text-sm font-medium text-white mb-3 block">
                      Recommendation
                    </label>
                    <Select defaultValue="all">
                      <SelectTrigger className="bg-white/10 border-white/20 text-white">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-gray-900 border-gray-700">
                        <SelectItem value="all">All Recommendations</SelectItem>
                        <SelectItem value="strong">Strong</SelectItem>
                        <SelectItem value="moderate">Moderate</SelectItem>
                        <SelectItem value="weak">Weak</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-3 space-y-6">
            {/* Project Header */}
            <div className="flex items-center gap-4 p-4 bg-white/5 rounded-xl border border-white/10">
              <Globe className="w-5 h-5" style={{ color: 'hsl(271 81% 56%)' }} />
              <span className="text-gray-300 font-medium">45+ locations • Atlanta, GA</span>
              <Badge className="bg-green-500/20 text-green-400 border-green-500/30 ml-auto">
                <Award className="w-3 h-3 mr-1" />
                AI Template Active
              </Badge>
            </div>

            {/* Metrics Cards */}
            <div className="grid grid-cols-4 gap-4">
              {[
                { label: "TOTAL", value: "0", color: "text-white", icon: Users },
                { label: "HIGH PRIORITY", value: "0", color: "#ff8c00", icon: Target },
                { label: "QUALIFIED", value: "0", color: "#22c55e", icon: Award },
                { label: "PE EXP", value: "0", color: "hsl(271 81% 56%)", icon: TrendingUp }
              ].map((metric, index) => (
                <div key={metric.label} className="bg-white/5 border border-white/10 rounded-xl p-6 text-center">
                  <div className="w-8 h-8 mx-auto mb-4 flex items-center justify-center">
                    <metric.icon className="w-6 h-6 text-gray-400" />
                  </div>
                  <div className="text-4xl font-bold mb-2" style={{ color: metric.color }}>
                    {metric.value}
                  </div>
                  <div className="text-xs text-gray-400 uppercase tracking-wider">
                    {metric.label}
                  </div>
                </div>
              ))}
            </div>

            {/* Main Content Area */}
            <div className="bg-white/5 border border-white/10 rounded-xl min-h-[400px] flex flex-col items-center justify-center text-center p-12">
              <div className="w-16 h-16 mb-6 flex items-center justify-center">
                <Users className="w-16 h-16 text-gray-500" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-4">
                No candidates yet
              </h3>
              <p className="text-gray-400 mb-8 max-w-lg leading-relaxed">
                Start a LinkedIn search to find CFO candidates for your TechMed Healthcare project. Our AI will analyze profiles and provide intelligent recommendations.
              </p>
              <Button size="lg" className="px-8 py-4 text-lg font-medium" style={{ backgroundColor: 'hsl(271 81% 56%)', color: 'white' }}>
                <Search className="w-5 h-5 mr-3" />
                Search LinkedIn Now
              </Button>
              
              {/* Three colored dots */}
              <div className="mt-8 flex items-center gap-6 text-sm text-gray-400">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  <span>AI-powered matching</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full" style={{ backgroundColor: 'hsl(271 81% 56%)' }}></div>
                  <span>Real-time results</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-cyan-500 rounded-full"></div>
                  <span>45+ location coverage</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;